INSERT INTO airlines (name, icao_code) VALUES
    ('American Airlines', 'AAL'),
    ('Delta Air Lines', 'DAL'),
    ('United Airlines', 'UAL'),
    ('Southwest Airlines', 'SWA'),
    ('Lufthansa', 'DLH'),
    ('Air France', 'AFR'),
    ('British Airways', 'BAW'),
    ('KLM Royal Dutch Airlines', 'KLM'),
    ('Turkish Airlines', 'THY'),
    ('Emirates', 'UAE'),
    ('Qatar Airways', 'QTR'),
    ('Singapore Airlines', 'SIA'),
    ('Cathay Pacific', 'CPA'),
    ('All Nippon Airways', 'ANA'),
    ('Etihad Airways', 'ETD'),
    ('Air Canada', 'ACA'),
    ('Alaska Airlines', 'ASA'),
    ('JetBlue Airways', 'JBU'),
    ('Aeroflot', 'AFL'),
    ('China Southern Airlines', 'CSN'),
    ('EasyJet', 'EZY'),
    ('Ryanair', 'RYR'),
    ('Norwegian Air Shuttle', 'NAX'),
    ('Aer Lingus', 'EIN'),
    ('Finnair', 'FIN'),
    ('Iberia', 'IBE'),
    ('Japan Airlines', 'JAL'),
    ('Korean Air', 'KAL'),
    ('LATAM Chile', 'LAN'),
    ('Malaysia Airlines', 'MAS'),
    ('Qantas', 'QFA'),
    ('Saudi Arabian Airlines', 'SVA'),
    ('Scandinavian Airlines', 'SAS'),
    ('Swiss International Air Lines', 'SWR'),
    ('TAP Air Portugal', 'TAP'),
    ('Thai Airways International', 'THA'),
    ('Vietnam Airlines', 'HVN'),
    ('Virgin Atlantic Airways', 'VIR'),
    ('Xiamen Airlines', 'CXA'),
    ('Philippine Airlines', 'PAL'),
    ('Asiana Airlines', 'AAR'),
    ('Air New Zealand', 'ANZ'),
    ('Alitalia', 'AZA'),
    ('Austrian Airlines', 'AUA'),
    ('Avianca', 'AVA'),
    ('Bangkok Airways', 'BKP'),
    ('Brussels Airlines', 'BEL'),
    ('Copa Airlines', 'CMP'),
    ('Czech Airlines', 'CSA'),
    ('Egyptair', 'MSR'),
    ('Аэрофлот', 'AFL'),
    ('Сибирь (S7 Airlines)', 'SBI'),
    ('Уральские авиалинии', 'SVR'),
    ('Победа', 'PBD'),
    ('Россия', 'SDM'),
    ('Якутия', 'SYL'),
    ('Аврора', 'SHU'),
    ('УТэйр', 'UTA'),
    ('Nordwind Airlines', 'NWS'),
    ('Red Wings Airlines', 'RWZ'),
    ('Азимут', 'AZO'),
    ('Smartavia', 'AUL'),
    ('Икар', 'IKT'),
    ('Severstal Air Company', 'SSF'),
    ('РусЛайн', 'RLU');
